name: Build docker images (scheduled)

on:
  push:
    branches:
      - docker-image*
  repository_dispatch:
  workflow_call:
    inputs:
      image_postfix:
        required: true
        type: string
  schedule:
    - cron: "0 1 * * *"

concurrency:
  group: docker-images-builds
  cancel-in-progress: false

jobs:
  latest-docker:
    name: "Latest PyTorch + TensorFlow [dev]"
    if: inputs.image_postfix != ''
    runs-on: ubuntu-latest
    steps:
      -
        name: Echo
        run: |
          echo "${{ inputs.image_postfix }}"
          echo "${{ github.event_name }}"
